# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cda7033ad5f619e5d5c6e2720c8df48e4196fab76e5311d3cba0538880c4f957febcd49e479501bf9fe98a0952ea4072a3096010ecc24333c2460feee07270b

test:
  secret_key_base: 384769696326e53bc606322870bbe6acd773a9fec9ca6e8c54f2684d552c3ca2a97fddc7b9ef823a88542a5829ca1e8b3754a5e14df49d50d2940e342b894487

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
